# Generated by Django 5.1.1 on 2024-09-28 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('Amenities_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galler_category',
            fields=[
                ('Galler_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('Offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, upload_to='gallery/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('Room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sayabout',
            fields=[
                ('Sayabout_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.CharField(max_length=100)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('chack_out', models.DateField(blank=True, null=True)),
                ('tatal_amount', models.CharField(max_length=100)),
                ('d_charge', models.CharField(max_length=500)),
                ('is_checkout', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('c_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlasHotal.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('Gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, upload_to='galleery/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlasHotal.galler_category')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=222, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='gallery/')),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlasHotal.room_type')),
            ],
        ),
    ]
